[build]
  base = "dealership-sim"
  command = "pnpm install && pnpm --filter=@dealership/shared build && pnpm --filter=@dealership/frontend build"
  publish = "frontend/dist"

[build.environment]
  VITE_API_BASE = "https://codex-dealersim-production.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

