[phases.setup]
nixPkgs = ["nodejs_18", "pnpm-9_x"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter=@dealership/backend build"]

[start]
cmd = "cd /app && node backend/dist/index.js"
