[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
