[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
