[build]
builder = "nixpacks"

[deploy]
startCommand = "node backend/dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
