[build]
builder = "nixpacks"

[deploy]
startCommand = "pnpm --filter=@dealership/backend start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
